Build system v1
vadyukkha/matrix_multiplication_algorithms_for_RISC-V pull request #1
Opened 2024-10-20 17:06 UTC by daniilparfenov

### Первая версия конфигурации билдовой системы проекта:
  - Два cmake файла: корневой и файл в /tests, где подгружается gtest
  - Есть возможность включать/отключать компиляцию тестов через флаг BUILD_TESTS (по умолчанию ON)

2024-10-21 18:13 UTC, FLTLN requested changes

2024-10-21 18:13 UTC, FLTLN commented on .gitignore
> +build
В конце файла должен быть перенос строки. Здесь и везде.

2024-10-21 18:13 UTC, FLTLN commented on CMakeLists.txt
> +file(GLOB SRC_FILES ${PROJECT_SOURCE_DIR}/src/*.c ${PROJECT_SOURCE_DIR}/API/*.cpp)
Включение этих исходников нужно перенести в отдельные файлы + немного поменять зависимости.

Библиотека с плюсовым апи должна зависеть от библиотеки с имплементациями алгоритмов. Предлагаю переименовать папку API - не стоит называть папку заглавными буквами. 

Инклюды для апи и внутренних реализаций тоже нужно растащить по разным include_directories - в апи-библиотеке не должны светиться внутренние хедера.

2024-10-22 13:58 UTC, daniilparfenov commented on .gitignore
> +build
done

2024-10-22 13:59 UTC, merged