Demo api
vadyukkha/matrix_multiplication_algorithms_for_RISC-V pull request #2
Opened 2024-10-23 13:00 UTC by vadyukkha

Добавлено:
1. API - содержит класс MatrixLib и методы, детали прописаны в спецификации. API Находится в папке api/
2. Тесты для API, написано 5 тестов: на конструкторы, геттеры и сеттеры, для копирования и сравнения матрицы, перемножения и ошибки. Находятся в папке tests/api_tests/
3. Добавлены примеры использования API в файл src/main.cpp

Изменено:
1. Переименованы файлы naive.h naive.c на matrix_operation.h matrix_operation.c соотвественно.
2. Функция matmul_naive больше не принимает float массивы, работает только с integer.
3. Функция matmul_naive теперь работает не только с квадратными матрицами.

Исправлено:
1.  Конфликты связанные с новыми изменениями в файлах tests/test1.cpp и tests/main.cpp

2024-10-25 10:52 UTC, daniilparfenov commented on tests/api_tests/test_exception_func.cpp
> +        assert(false && "Exception was not thrown as expected!");
По идее, проверять выброс исключений стоит без ассертов, чтобы в случае если тест валится, все тестирование не завершалась. Я бы сделал как [тут](https://stackoverflow.com/questions/23270078/test-a-specific-exception-type-is-thrown-and-the-exception-has-the-right-propert). 2 способ с `FAIL() << "Err text";` как по мне лучше всего. По остальным ассертам в этом файле аналогично.

2024-10-25 10:52 UTC, daniilparfenov commented on tests/api_tests/test_product_func.cpp
> +        EXPECT_EQ(false, true);
Аналогично сделать через `FAIL()`, без костылей :)

2024-10-25 10:52 UTC, daniilparfenov commented on tests/api_tests/test_setSize_func.cpp
> +        EXPECT_EQ(false, true);
`FAIL()`

2024-10-27 13:26 UTC, FLTLN requested changes

2024-10-27 13:26 UTC, FLTLN commented on api/matrix_lib.cpp
> +Matrix::Matrix(const int rows, const int cols) {
Проверку размера на положительность можно не выполнять, если использовать в прототипе тип данных, который не может быть отрицательным.

2024-10-27 13:26 UTC, FLTLN commented on api/matrix_lib.cpp
> +    for (size_t i = 0; i < rows && i < rows_; ++i) {
Можно реализовать без циклов.

2024-10-27 13:26 UTC, FLTLN commented on api/matrix_lib.cpp
> +size_t Matrix::getRows() const noexcept { return rows_; }
Из названия не очевидно что возвращает количество строк в матрице.

2024-11-03 09:57 UTC, LevPogromov approved these changes

2024-11-03 09:59 UTC, daniilparfenov approved these changes

2024-11-04 17:50 UTC, FLTLN requested changes

2024-11-04 17:50 UTC, FLTLN commented on CMakeLists.txt
> +endif()
EOL at EOF
check other files too

2024-11-04 17:50 UTC, FLTLN commented on api/matrix_lib.cpp
> +        throw std::invalid_argument("Size must be positive");
In future we need get rid of std::<something> as exception and use fully custom ones
it is needed for user to understand that exactly this lib throw an exception
see for example: https://www.geeksforgeeks.org/how-to-throw-custom-exception-in-cpp/

2024-11-04 17:50 UTC, FLTLN commented on benchmarking/benchmarking_naive.c
Should be in separate PR

2024-11-07 13:26 UTC, FLTLN approved these changes

2024-11-08 05:33 UTC, merged