Add benchmarking
vadyukkha/matrix_multiplication_algorithms_for_RISC-V pull request #6
Opened 2024-11-23 18:06 UTC by LevPogromov

1)Создали бенчмарк для наивной реализации перемножения матриц, основанный на медиане подсчитанных тактов работы
2)Написан скрипт для генерации графика

2024-11-23 19:40 UTC, daniilparfenov requested changes

2024-11-23 19:40 UTC, daniilparfenov commented on .gitignore
Мне кажется, лучше создать отдельную папку под вывод скрипта для создания графа и уже ее закинуть в гитигнор

2024-11-23 19:40 UTC, daniilparfenov commented on .gitignore
аналогично с выводом бенчмарка в файл. Можно все это в одну папку benchmarking_output закинуть

2024-11-23 19:40 UTC, daniilparfenov commented on benchmarking/create_graph.py
> +if "__main__" == __name__:
думаю, будет лучше, если разгрузить main и вынести хотя бы создание графа в отдельную функцию

2024-11-23 19:40 UTC, daniilparfenov commented on benchmarking/create_graph.py
я бы добавил requirements.txt с учетом того, что стал необходим matplotlib

2024-11-23 21:39 UTC, vadyukkha approved these changes

2024-11-24 10:09 UTC, FLTLN approved these changes
Can be merged after other comments is done.

2024-11-24 12:20 UTC, merged